version: '3'

services:
  db:
    build: postgres
    image: mypost
  web:
    build: web
    image: webapp
    ports:
      - "8080:80"
  migrations:
    image: webapp
    command: ./wait-for-it.sh db:5432 -- python3 /home/docker/code/manage.py migrate
    depends_on:
      - db
      - web
  run:
    image: webapp
    command: supervisord -n
    ports:
      - "8080:80"
    depends_on:
      - migrations
      - db
      - web
    

